### ISSUE TITLE
I can help

### ISSUE THREAD

**Issue by DevTech2008** [AVCADO/SleepyOS#1]
Sorry I know this isn't how I should contact you but I saw in a Discord server that this is for Python and Ai and I am pretty decent at that so I just wanted to contact you if you wanted any help sent a friend request on discord my ign is Dev_.#5437

**Comment by Vresod** [comment]
https://discord.gg/RMXxjgG

**Comment by Vresod** [comment]
server with avcado in it

**Comment by Vresod** [comment]
@AVCADO pls rejoin server

**Comment by AVCADO** [comment]
no
