### ISSUE TITLE
Theft of code

### ISSUE THREAD

**Issue by rizet** [AVCADO/SleepyOS#4]
You stole [my code](https://github.com/microNET-OS/microCORE) and didn't give credit. As well, your repo is missing a license, which automatically licenses it as All Rights Reserved. I licensed my code under GPLv3, so you must license your repo under GPLv3.

Very disappointed. You stole literally everything and changed the filenames. You claim that the kernel is written in "pure C", however you stole my code and my code contains no C code whatsoever.

**Comment by Vresod** [comment]
xd

**Comment by AVCADO** [comment]
I will license it under GPLv3 dont worry

yes i havent modified the readme
