### ISSUE TITLE
Codebase contains cpp files

### ISSUE THREAD

**Issue by gordonfreeman424** [AVCADO/SleepyOS#5]
This isn't a C project, it's C++

Why is it labelled as C

**Comment by AVCADO** [comment]
jesus christ i haven't updated the readme
#4 
read my comment.

**Comment by gordonfreeman424** [comment]
BOOOOOOOOOOOOOOOO REWRITE IT IN C

**Comment by AVCADO** [comment]
no. if you would like to do that, well, you can. I'm not going to.
