### ISSUE TITLE
rewrite this in ><>

### ISSUE THREAD

**Issue by Asoina** [AVCADO/SleepyOS#6]
also join discord back

**Comment by AVCADO** [comment]
no

**Comment by ZenithiumDev** [comment]
lmfao

**Comment by AVCADO** [comment]
please stop flooding me with retarded issues
i'm trying to get a os working here

**Comment by Asoina** [comment]
we wouldn't have to if you just rejoined discord and stop acting like a retard

**Comment by AVCADO** [comment]
i don't want to back to discord.

**Comment by Vresod** [comment]
![image](https://user-images.githubusercontent.com/40863375/97373710-f5027880-188c-11eb-9cd4-bae7d259841b.png)
@AVCADO

**Comment by AVCADO** [comment]
alright fine. i'm coming back.

**Comment by AVCADO** [comment]
but you better not be lying

**Comment by Vresod** [comment]
im not
![image](https://user-images.githubusercontent.com/40863375/97374223-3a737580-188e-11eb-839f-b0232b7b0e40.png)

**Comment by AVCADO** [comment]
no not that account

**Comment by Vresod** [comment]
lol

**Comment by AVCADO** [comment]
that ones dead

**Comment by AVCADO** [comment]
avc_dev#2399

**Comment by AVCADO** [comment]
make that one admin
